Catch deploy errors

diff --git a/.github/workflows/prod_deploy.yaml b/.github/workflows/prod_deploy.yaml
--- a/.github/workflows/prod_deploy.yaml
+++ b/.github/workflows/prod_deploy.yaml
@@ -13,7 +13,7 @@ jobs:
               -H "Authorization: Bearer ${{ secrets.CI_TOKEN }}" \
               -H "Content-Type:application/json" \
               -d '{"steps": ["deploy_auth", "deploy_batch", "deploy_ci", "deploy_hailgenetics_image", "deploy_memory", "deploy_wheel", "upload_query_jar"], "sha": "${{ github.sha }}"}' \
-              https://ci.hail.populationgenomics.org.au/api/v1alpha/prod_deploy)
+              https://ci.hail.populationgenomics.org.au/api/v1alpha/prod_deploy || echo 'Failed to deploy')
           echo DEPLOY_BATCH_URL_GCP=$DEPLOY_BATCH_URL >> $GITHUB_ENV
 
       - name: deploy to Azure
@@ -23,7 +23,7 @@ jobs:
               -H "Authorization: Bearer ${{ secrets.CI_TOKEN_AZURE }}" \
               -H "Content-Type:application/json" \
               -d '{"steps": ["deploy_auth", "deploy_batch", "deploy_ci", "deploy_memory", "upload_query_jar"], "sha": "${{ github.sha }}"}' \
-              https://ci.azhail.popgen.rocks/api/v1alpha/prod_deploy)
+              https://ci.azhail.popgen.rocks/api/v1alpha/prod_deploy || echo 'Failed to deploy')
           echo DEPLOY_BATCH_URL_AZURE=$DEPLOY_BATCH_URL >> $GITHUB_ENV
 
       - name: post to Slack
